### PR TITLE
Add landscape orientation

### PR DESCRIPTION
**Pull request by wtao-mux**

### CODE REVIEW

**Comment by wtao-mux** [comment]
changes

1. move LFLiveKit outside of cocopods to become a xcode project itself
2. enable all device orientation
3. lock the screen rotation when live capturing starts, and release the lock after capture is closed
4. pass UIInterfaceOrientation to LFLiveKit's LFLiveVideoConfiguration.defaultConfiguration call so that captured images are sized properly

**Comment by heff** [comment]
Why are so many files changing in this PR? Should we be git-ignoring something?

**Comment by wtao-mux** [comment]
@heff basically those files are entire set of the LFLiveKit. i need to extract them from cocopods so that i can modify them

**Comment by heff** [comment]
Ok, that approach though makes it hard to tell where you made changes to LFLiveKit, and hard to push any improvements back to LFLiveKit if we want. Tell me if you think this approach would work.

1. Make a Mux fork of LFLiveKit.
2. Commit changes to the Mux fork with clear commits that show what changed
3. [Point pods to our fork for LFLiveKit](http://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo)
4. If what we're changing about LFLiveKit is improving it, make a pull request back to LFLiveKit from our fork.

**Comment by wtao-mux** [comment]
@heff it make perfect sense

**Comment by wtao-mux** [comment]
find a better way to support all orientation without change the LFLivekit. Close this for now. open a new one soon

**Pull request closed without merging**
